services:
  backend-app:
    build: ./backend
    volumes:
      - ./information_store:/backend/information_store
      - ./vectorstore:/backend/vectorstore
    ports:
      - "8087:8087"
    environment:
      - BASE_PATH=${PWD}
  frontend-app:
    build: ./chatbot
    ports:
      - "8501:8501"
    # deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: 1
    #          capabilities: [gpu]