services:
  backend-app:
    build: ./backend
    volumes:
      - ./information_store:/backend/information_store
    ports:
      - "8087:8087"
    environment:
      - BASE_PATH=${PWD}
  frontend-app:
    build: ./chatbot
    ports:
      - "8085:8085"
    # deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: 1
    #          capabilities: [gpu]